/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9c70874f-a0ba-4fe1-bc71-c71f7d553535",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_jPcy8UWEX",
    "aws_user_pools_web_client_id": "115nqn22rgajhb9g02h9hnve2k",
    "oauth": {
        "domain": "social-media-site-testenv.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
